### ISSUE TITLE
TDD dataset

### ISSUE THREAD

**Issue by LonglongaaaGo** [ZZZHANG-jx/Recommendations-Document-Image-Processing#4]
Hi @ZZZHANG-jx ,

Thank you so much for your awesome work.
The TDD dataset is not available, could you share it with your copy?
[TDD (text deblur dataset)](https://www.fit.vut.cz/research/publication-file/10922/hradis15CNNdeblurring.pdf)

I will cite your [DocRe](https://github.com/ZZZHANG-jx/DocRes/tree/master) for comparison.
Thanks!

**Comment by ZZZHANG-jx** [comment]
Hi @LonglongaaaGo ,

I have uploaded the TDD dataset to OneDrive: [TDD Dataset](https://1drv.ms/u/s!Ak15mSdV3Wy4ia5RzoEMszb2hGlxbQ?e=tQA6IW).

Please note that I do not have the original files anymore, so the file structure might be different from the original dataset.

Thanks!

**Comment by LonglongaaaGo** [comment]
I really appreciate it.
Thanks!

**Comment by MikeQ0425** [comment]
Thank you so much for your awesome work. At present, it seems that neither of the two links can be downloaded. May I ask if you have any latest download methods to provide?

**Comment by ZZZHANG-jx** [comment]
> Thank you so much for your awesome work. At present, it seems that neither of the two links can be downloaded. May I ask if you have any latest download methods to provide?

This link2 https://1drv.ms/u/c/b86cdd552799794d/EQoovhEeCLVMpaeZyVWQyOoBBRsPGXHYOHteZ78q_XYszw?e=fs31YD seems ok for me.  If you're in China, you might need to set up an appropriate proxy as it is a onedrive link.
