### ISSUE TITLE
关于论文的问题

### ISSUE THREAD

**Issue by zhaozhaoooo** [ZZZHANG-jx/Recommendations-Document-Image-Processing#6]
请问作者这些论文都看过吗？看了前辈的论文，感觉你在文档处理领域研究的很深刻，一定看了超多文献。从marior开始关注你，发现你真的做了很多出彩的工作。
想问问最近有没有读ICASSP那篇同时做dewarp和enhancement的工作：[Efficient Joint Rectification of Photometric and Geometric Distortions in Document Images](https://ieeexplore.ieee.org/abstract/document/10447446)
这篇文章我没有找到一作的联系方式，看了这篇有一些问题，想要探讨一下。这篇文章采用了双流架构，一个分支预测backward map，一个分支预测增强后的文档。文章中说输入图像尺寸为224*224，对于backward map来说，一个简单的双线性上采样肯定是够的，但是对于enhancement来说，肯定不够吧。如果训练采用224*224，推理使用原图尺寸的话，enhancement可能够用了，但是对于backward map就会产生灾难性的变形。所以我很好奇作者这里是怎么处理的，然而也没开源。所以想问问前辈这里有什么好的想法吗？

**Comment by ZZZHANG-jx** [comment]
> 请问作者这些论文都看过吗？看了前辈的论文，感觉你在文档处理领域研究的很深刻，一定看了超多文献。从marior开始关注你，发现你真的做了很多出彩的工作。 想问问最近有没有读ICASSP那篇同时做dewarp和enhancement的工作：[Efficient Joint Rectification of Photometric and Geometric Distortions in Document Images](https://ieeexplore.ieee.org/abstract/document/10447446) 这篇文章我没有找到一作的联系方式，看了这篇有一些问题，想要探讨一下。这篇文章采用了双流架构，一个分支预测backward map，一个分支预测增强后的文档。文章中说输入图像尺寸为224_224，对于backward map来说，一个简单的双线性上采样肯定是够的，但是对于enhancement来说，肯定不够吧。如果训练采用224_224，推理使用原图尺寸的话，enhancement可能够用了，但是对于backward map就会产生灾难性的变形。所以我很好奇作者这里是怎么处理的，然而也没开源。所以想问问前辈这里有什么好的想法吗？

根据论文的说法应该是全图resize成224x224训练，前向则采用原图尺寸 or 1024x1024。

这个做法感觉对enhancement来说也是有些问题的，应该比crop出224x224的patch来训练效果要差。此外还有一个需要注意的点是，LD和MS-SSIM这两个指标都会把图像缩放到598400个像素后再进行指标的评价，这一点可能有助于减轻这个问题给enhancement任务带来的影响。

对于bm的预测来说，之前的经验是遇到训练测试分辨率不一致的时候bm的预测会有比较明显的退化，但可能可以通过一些设计缓解这一问题，这点值得继续研究。
